# Generated by Django 4.1.7 on 2023-10-21 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SemiTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('production_year', models.DateField()),
                ('registration_number', models.CharField(max_length=9, unique=True)),
                ('semi_note', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('available', models.CharField(choices=[('Wolny', 'Wolny'), ('Zajety', 'Zajety'), ('Awaria', 'Awaria')], default='Wolny', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SemiTrailerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belts', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('corners', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(16)])),
                ('aluminium_stick', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(20)])),
                ('wide_stick', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('ladder', models.BooleanField(default=True)),
                ('roof_stick', models.BooleanField(default=True)),
                ('dimenstion_board', models.BooleanField(default=True)),
                ('semi_trailer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SemitruckManage.semitrailer')),
            ],
        ),
    ]
