# Generated by Django 4.1.7 on 2023-08-01 20:41

import Applications.SemitruckManage.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SemitruckManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semitrailer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='semitrailerequipment',
            name='status',
            field=models.CharField(choices=[('Wolny', 'Wolny'), ('Zajety', 'Zajety'), ('Awaria', 'Awaria')], default='Wolny', max_length=6),
        ),
        migrations.AlterField(
            model_name='semitrailer',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[Applications.SemitruckManage.validators.registration_num_validator]),
        ),
        migrations.AlterField(
            model_name='semitrailerequipment',
            name='semi_trailer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SemitruckManage.semitrailer'),
        ),
    ]
