# Generated by Django 4.1.7 on 2023-08-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemitruckManage', '0003_semitrailer_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semitrailer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
