# Generated by Django 4.1.7 on 2023-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SemitruckManage', '0004_alter_semitrailer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semitrailer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
