# Generated by Django 4.1.7 on 2023-08-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SemitruckManage', '0005_alter_semitrailer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semitrailerequipment',
            old_name='status',
            new_name='available',
        ),
    ]
