# Generated by Django 4.1.7 on 2023-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SemitruckManage', '0006_rename_status_semitrailerequipment_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semitrailerequipment',
            old_name='available',
            new_name='status',
        ),
    ]
