# Generated by Django 4.1.7 on 2023-10-21 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 12, 48, 27, 917716))),
                ('status', models.CharField(choices=[('Accident', 'Accident'), ('Proggres', 'In progess'), ('Finish', 'Finished')], default='Proggres', max_length=10)),
                ('date_finished', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 21, 12, 48, 27, 917716))),
                ('receivment_type', models.CharField(choices=[('from_driver', 'From Driver to Manager'), ('from_manager', 'From manager to Driver')], default='from_manager', max_length=12)),
                ('truck_complain', models.CharField(blank=True, max_length=300)),
                ('semi_trailer_complain', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivmentLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(blank=True, max_length=40)),
                ('apartment_number', models.CharField(blank=True, max_length=6)),
                ('geo_address', models.CharField(blank=True, max_length=30)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivment')),
            ],
        ),
        migrations.CreateModel(
            name='SemiTrailerReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivment')),
            ],
        ),
        migrations.AddField(
            model_name='receivment',
            name='destination',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivmentlocations'),
        ),
    ]
