# Generated by Django 4.1.7 on 2023-08-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TruckManage', '0006_alter_truck_photo'),
        ('SemitruckManage', '0005_alter_semitrailer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('truck_complain', models.CharField(max_length=300)),
                ('semi_trailer_complain', models.CharField(max_length=300)),
                ('semi_trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SemitruckManage.semitrailer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('transferring_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferring_user', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TruckManage.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivment')),
            ],
        ),
        migrations.CreateModel(
            name='SemiTrailerReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('receivment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivment')),
            ],
        ),
    ]
