# Generated by Django 4.1.7 on 2023-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceivmentManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivment',
            name='semi_trailer_complain',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='truck_complain',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
