# Generated by Django 4.1.7 on 2023-10-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReceivmentManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SemitruckManage', '0001_initial'),
        ('TruckManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivment',
            name='destination_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivment',
            name='semi_trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SemitruckManage.semitrailer'),
        ),
        migrations.AddField(
            model_name='receivment',
            name='source_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivment',
            name='truck',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TruckManage.truck'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='receivment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceivmentManage.receivment'),
        ),
    ]
