# Generated by Django 4.1.7 on 2023-10-25 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceivmentManage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 21, 9, 45, 209041)),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 25, 21, 9, 45, 210040)),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='receivment_type',
            field=models.CharField(choices=[('from_driver', 'Driver'), ('from_manager', 'Manager')], default='from_manager', max_length=12),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='status',
            field=models.CharField(choices=[('Accident', 'Accident'), ('Proggres', 'In Progess'), ('Finish', 'Finished')], default='Proggres', max_length=10),
        ),
    ]
