# Generated by Django 4.1.7 on 2023-08-31 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReceivmentManage', '0002_alter_receivment_semi_trailer_complain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='receivment',
            name='transferring_user',
        ),
        migrations.AddField(
            model_name='receivment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 21, 14, 45, 54891)),
        ),
        migrations.AddField(
            model_name='receivment',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 21, 14, 45, 54891)),
        ),
        migrations.AddField(
            model_name='receivment',
            name='destination_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivment',
            name='receivment_type',
            field=models.CharField(choices=[('from_driver', 'From Driver to Manager'), ('from_manager', 'From manager to Driver')], default='from_driver', max_length=12),
        ),
        migrations.AddField(
            model_name='receivment',
            name='source_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='status',
            field=models.CharField(choices=[('Accident', 'Accident'), ('Proggres', 'In progess'), ('Finish', 'Finished')], default='Proggres', max_length=10),
        ),
    ]
