# Generated by Django 4.1.7 on 2023-11-06 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceivmentManage', '0004_receivmentlocations_final_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 23, 41, 21, 814316)),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 6, 23, 41, 21, 815319)),
        ),
        migrations.AlterField(
            model_name='receivmentlocations',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
