# Generated by Django 4.1.7 on 2023-11-09 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceivmentManage', '0005_locationhistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 26, 57, 455471)),
        ),
        migrations.AlterField(
            model_name='receivment',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 17, 26, 57, 455471)),
        ),
    ]
