# Generated by Django 4.1.7 on 2023-10-21 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=40)),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(999)])),
                ('registration_number', models.CharField(max_length=9, unique=True)),
                ('driven_length', models.IntegerField()),
                ('production_date', models.DateField()),
                ('available', models.CharField(choices=[('Wolny', 'Wolny'), ('Zajety', 'Zajety'), ('Awaria', 'Awaria')], default='Wolny', max_length=6)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='TruckEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.BooleanField(default=True)),
                ('chains', models.BooleanField(default=True)),
                ('jack_hitch', models.BooleanField(default=True)),
                ('planetar_key', models.BooleanField(default=True)),
                ('manometer', models.BooleanField(default=True)),
                ('tire_pumping_wire', models.BooleanField(default=True)),
                ('complete_status', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TruckManage.truck')),
            ],
        ),
    ]
