# Generated by Django 4.1.7 on 2023-07-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TruckManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.BooleanField(default=True)),
                ('chains', models.BooleanField(default=True)),
                ('jack_hitch', models.BooleanField(default=True)),
                ('planetar_key', models.BooleanField(default=True)),
                ('manometer', models.BooleanField(default=True)),
                ('tire_pumping_wire', models.BooleanField(default=True)),
                ('complete_status', models.BooleanField(default=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TruckManage.truck')),
            ],
        ),
    ]
