# Generated by Django 4.1.7 on 2023-08-01 20:41

import Applications.TruckManage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckManage', '0002_truckequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckequipment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[Applications.TruckManage.validators.registration_num_validator]),
        ),
    ]
