# Generated by Django 4.1.7 on 2023-08-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckManage', '0003_truckequipment_photo_alter_truck_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='avaiable',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
