# Generated by Django 4.1.7 on 2023-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckManage', '0004_rename_avaiable_truck_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
