# Generated by Django 4.1.7 on 2023-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruckManage', '0005_truck_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
