# Generated by Django 4.1.7 on 2023-07-23 20:52

import Applications.UserManage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0002_customuser_avaiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apartment_number',
            field=models.CharField(max_length=5, validators=[Applications.UserManage.validators.apartment_house_num_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=30, validators=[Applications.UserManage.validators.street_name_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=40, validators=[Applications.UserManage.validators.street_name_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(max_length=5, validators=[Applications.UserManage.validators.apartment_house_num_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[Applications.UserManage.validators.street_name_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(max_length=30, validators=[Applications.UserManage.validators.street_name_validator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[Applications.UserManage.validators.street_name_validator]),
        ),
    ]
